#include "typed_tiebreaking_open_list.h"

#include "open_list.h"

#include "../option_parser.h"
#include "../plugin.h"

#include "../utils/rng.h"
#include "../utils/memory.h"
#include "../utils/system.h"

#include <cassert>
#include <deque>
#include <map>
#include <utility>
#include <vector>
#include <iostream>

using namespace std;

template<class Entry>
TypedTiebreakingOpenList<Entry>::TypedTiebreakingOpenList(const Options &opts)
    : TieBreakingOpenList<Entry>(opts),
      type_evaluators(opts.get_list<ScalarEvaluator *>("type_evals")),
      stochastic(opts.get<bool>("stochastic")){
}

template<class Entry>
void TypedTiebreakingOpenList<Entry>::do_insertion(
    EvaluationContext &eval_context, const Entry &entry) {
    Key key;
    key.reserve(this->evaluators.size());
    for (ScalarEvaluator *evaluator : this->evaluators)
        key.push_back(eval_context.get_heuristic_value_or_infinity(evaluator));
    Key type_key;
    type_key.reserve(type_evaluators.size());
    for (ScalarEvaluator *evaluator : type_evaluators)
        type_key.push_back(eval_context.get_heuristic_value_or_infinity(evaluator));
    auto &tbuckets = buckets[key];
    auto &tbucket = tbuckets[type_key];
    tbucket.push_back(entry);
    assert(!tbucket.empty());
    assert(!tbuckets.empty());
    assert(!buckets.empty());
    ++(this->size);
}

template<class Entry>
Entry TypedTiebreakingOpenList<Entry>::remove_min(vector<int> *key) {
    assert(this->size > 0);
    --(this->size);
    assert(!buckets.empty());
    auto it = buckets.begin();  // sorted buckets
    assert(it != buckets.end());
    assert(!it->second.empty());
    if (key) {
        assert(key->empty());
        *key = it->first;
    }
    auto &tbuckets = it->second;
    assert(!tbuckets.empty());
    auto it2 = stochastic ? tbuckets.iter_random() : tbuckets.iter_next();
    auto &tbucket = it2->second;
    assert(!tbucket.empty());
    
    Entry result = pop_bucket<Entry,Bucket<Entry>>(tbucket, this->queue_type);
    if (tbucket.empty()){
        tbuckets.erase(it2);
        if (tbuckets.empty()){
            buckets.erase(it);
        }
    }
    return result;
}

template<class Entry>
bool TypedTiebreakingOpenList<Entry>::is_dead_end(
    EvaluationContext &eval_context) const {
    if (!this->evaluators.empty()){
        return TieBreakingOpenList<Entry>::is_dead_end(eval_context);
    } else {
        return false;
    }
}

template<class Entry>
void TypedTiebreakingOpenList<Entry>::get_involved_heuristics(
    set<Heuristic *> &hset) {
    for (ScalarEvaluator *evaluator : this->evaluators) {
        evaluator->get_involved_heuristics(hset);
    }
    for (ScalarEvaluator *evaluator : type_evaluators) {
        evaluator->get_involved_heuristics(hset);
    }
}

    

TypedTiebreakingOpenListFactory::TypedTiebreakingOpenListFactory(const Options &options)
    : options(options) {
}

unique_ptr<StateOpenList>
TypedTiebreakingOpenListFactory::create_state_open_list() {
    return Utils::make_unique_ptr<TypedTiebreakingOpenList<StateOpenListEntry>>(options);
}

unique_ptr<EdgeOpenList>
TypedTiebreakingOpenListFactory::create_edge_open_list() {
    return Utils::make_unique_ptr<TypedTiebreakingOpenList<EdgeOpenListEntry>>(options);
}

static shared_ptr<OpenListFactory> _parse(OptionParser &parser) {
    parser.document_synopsis("Typed Tie-breaking open list",
                             "Select a bucket with minimum <evals>,"
                             "then within the bucket, diversify the search among type buckets."
                             "Each type bucket labeled by the values of <type_evals>.");
    parser.add_list_option<ScalarEvaluator *>("evals",
                                              "Scalar evaluators."
                                              "Results are sorted according to the dictionary order,"
                                              "preferring smaller numbers.");
    parser.add_list_option<ScalarEvaluator *>("type_evals", "Scalar evaluators. "
                                              "Used to form the keys for the type buckets.");
    add_queue_type_option_to_parser(parser);
    parser.add_option<bool>(
        "pref_only",
        "insert only nodes generated by preferred operators", "false");
    parser.add_option<bool>(
        "unsafe_pruning",
        "allow unsafe pruning when the main evaluator regards a state a dead end",
        "true");
    parser.add_option<bool>(
        "stochastic",
        "If true, type buckets are selected at random."
        "Otherwise, loop over the type buckets, i.e., "
        "the last type bucket is selected in the first iteration, then "
        "the second last type bucket is selected in the second iteration and so on."
        "After the first type bucket is selected, select the last type bucket again."
        , "true");
    Options opts = parser.parse();
    // opts.verify_list_non_empty<ScalarEvaluator *>("evals");
    if (!opts.is_help_mode()){
        auto evals = opts.get<std::vector<ScalarEvaluator *>>("evals");
        auto type_evals = opts.get<std::vector<ScalarEvaluator *>>("type_evals");
        if (evals.empty() && type_evals.empty()){
            std::cout << "Error: unexpected empty list!" << std::endl
                      << "Both evals and type_evals are empty" << std::endl;
            Utils::exit_with(Utils::ExitCode::INPUT_ERROR);
        }
    }

    if (parser.dry_run())
        return nullptr;
    else
        return make_shared<TypedTiebreakingOpenListFactory>(opts);
}

static PluginShared<OpenListFactory> _plugin("typed_tiebreaking", _parse);
